# helm/airflow/values.yaml
executor: "CeleryExecutor"

webserverSecretKeySecretName: "airflow-webserver-secret"

postgresql:
  enabled: false

data:
  metadataSecretName: "my-airflow-db-secret"

config:
  core:
    load_examples: "False"
  celery:
    worker_concurrency: "2"



webserver:
  service:
    type: ClusterIP

workers:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

rbac:
  create: true


dags:
  gitSync:
    enabled: true
    repo: "https://github.com/MichaelHomme/azure-dataplatform-pipelines.git"
    branch: "main"
    subPath: "dags"
    credentialsSecret: "airflow-git-credentials"