apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-dbt-runtime-secrets
  namespace: "${AKS_AIRFLOW_NAMESPACE}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store

  target:
    name: dbt-runtime-secrets
    creationPolicy: Owner

  data:
    - secretKey: DBT_USER
      remoteRef:
        key: DBT-USER
    - secretKey: DBT_SECRET
      remoteRef:
        key: DBT-SECRET
