apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-git-credentials
  namespace: "${AKS_AIRFLOW_NAMESPACE}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store

  target:
    name: airflow-git-credentials
    creationPolicy: Owner
    template:
      data:
        GITSYNC_USERNAME: MichaelHomme
        GITSYNC_PASSWORD: "{{ .gitpat }}"

  data:
    - secretKey: gitpat
      remoteRef:
        key: AIRFLOW-GIT-PAT
